import {
	siSvelte,
	siTypescript,
	siJavascript,
	siTailwindcss,
	siPostgresql,
	siPrisma,
	siDocker,
	siNodedotjs,
	siReact,
	siNextdotjs,
	siVuedotjs,
	siGo,
	siPython,
	siRust,
	siGit,
	siGithub,
	siNginx,
	siRedis,
	siMongodb,
	siGraphql,
	siCloudflare,
	siLinux,
	siVercel,
	siSupabase,
	siDrizzle
} from 'simple-icons';
import type { SimpleIcon } from 'simple-icons';

const ICON_MAP: Record<string, SimpleIcon> = {
	svelte: siSvelte,
	sveltekit: siSvelte,
	typescript: siTypescript,
	javascript: siJavascript,
	'tailwind css': siTailwindcss,
	tailwindcss: siTailwindcss,
	tailwind: siTailwindcss,
	postgresql: siPostgresql,
	postgres: siPostgresql,
	prisma: siPrisma,
	docker: siDocker,
	'node.js': siNodedotjs,
	nodejs: siNodedotjs,
	react: siReact,
	'next.js': siNextdotjs,
	nextjs: siNextdotjs,
	'vue.js': siVuedotjs,
	vuejs: siVuedotjs,
	vue: siVuedotjs,
	go: siGo,
	golang: siGo,
	python: siPython,
	rust: siRust,
	git: siGit,
	github: siGithub,
	nginx: siNginx,
	redis: siRedis,
	mongodb: siMongodb,
	graphql: siGraphql,
	cloudflare: siCloudflare,
	linux: siLinux,
	vercel: siVercel,
	supabase: siSupabase,
	drizzle: siDrizzle
};

export function getTechIcon(name: string): SimpleIcon | null {
	return ICON_MAP[name.toLowerCase()] ?? null;
}
